# -*- coding: utf-8 -*-
"""hate_speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Wkn7iurEJqyNmlG3c97E7Aimyq570Iy
"""

!pip install -q transformers datasets evaluate accelerate scikit-learn

# The imports are moved to the next cell to ensure they are available for the seed_everything function.
# import random, torch, numpy as np
# from datasets import load_dataset
# from transformers import (
#     AutoTokenizer, AutoModelForSequenceClassification,
#     Trainer, TrainingArguments, DataCollatorWithPadding
# )
# import evaluate

import random, torch, numpy as np # Moved imports from the previous cell
from datasets import load_dataset # Moved imports from the previous cell
from transformers import ( # Moved imports from the previous cell
    AutoTokenizer, AutoModelForSequenceClassification, # Moved imports from the previous cell
    Trainer, TrainingArguments, DataCollatorWithPadding # Moved imports from the previous cell
) # Moved imports from the previous cell
import evaluate # Moved imports from the previous cell


def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
seed_everything()

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"🚀 Using device: {device}")

dataset = load_dataset("textdetox/multilingual_toxicity_dataset")

# Use only first 2000 samples for speed
# small_train = dataset["train"].shuffle(seed=42).select(range(1800))
# small_test  = dataset["train"].shuffle(seed=43).select(range(1800, 2000))

# Modified to use the 'en' split as 'train' split does not exist
small_train = dataset["en"].shuffle(seed=42).select(range(1800))
small_test  = dataset["en"].shuffle(seed=43).select(range(1800, 2000))


def process(ex):
    return {"text": ex.get("text", ""), "label": int(ex.get("toxic", 0))}

small_train = small_train.map(process, remove_columns=small_train.column_names)
small_test  = small_test.map(process, remove_columns=small_test.column_names)

model_name = "xlm-roberta-base"  # multilingual transformer
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

train_tok = small_train.map(tokenize, batched=True)
test_tok  = small_test.map(tokenize, batched=True)

model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2).to(device)
collator = DataCollatorWithPadding(tokenizer)

acc = evaluate.load("accuracy")
f1 = evaluate.load("f1")

def compute_metrics(p):
    preds = np.argmax(p.predictions, axis=1)
    return {
        "accuracy": acc.compute(predictions=preds, references=p.label_ids)["accuracy"],
        "f1_macro": f1.compute(predictions=preds, references=p.label_ids, average="macro")["f1"]
    }

args = TrainingArguments(
    output_dir="./hate_speech_small_model",
    eval_strategy="epoch", # Corrected argument name
    save_strategy="no",
    learning_rate=3e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    logging_steps=10,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_tok,
    eval_dataset=test_tok,
    tokenizer=tokenizer,
    data_collator=collator,
    compute_metrics=compute_metrics,
)

trainer.train()
print("✅ Final Evaluation:")
print(trainer.evaluate())

# ------------------------------------------------------------
# 🔍 Test the model with your own sentences
# ------------------------------------------------------------

# Define a few example texts to test
test_texts = [
    "I love you so much!",
    "You are a wonderful person.",
    "Go back to your country.",
    "Have a nice day!",
]

# Tokenize and predict
inputs = tokenizer(test_texts, return_tensors="pt", padding=True, truncation=True).to(device)
outputs = model(**inputs)
preds = torch.argmax(outputs.logits, dim=1).cpu().numpy()

# Display predictions
for text, pred in zip(test_texts, preds):
    label = "🟥 HATE / TOXIC" if pred == 1 else "🟩 NOT HATE"
    print(f"Text: {text}\n→ Prediction: {label}\n")